---
- name: SET ROUTER BANNERS
  hosts: routers
  gather_facts: no

  tasks:

    - name: LOAD BANNER ONTO NETWORK DEVICE
      ios_banner:
        banner: login
        text: |
          "{{ network_banner }}"
        state: present
